version: "3.8"
services:
  
  
  database:
    image: postgres:15.3-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
