logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO


# Spring Boot configuration
spring:
  profiles:
    active: development
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      platform: postgres
      mode: always
springdoc:
  api-docs: 
    path: /v3/api-docs

server:
  port: 8083
